
en:
  system: "You are an accurate and reliable AI assistant that can answer questions with the help of external documents. Please note that external documents may contain noisy or factually incorrect information. If the information in the document contains the correct answer, you will give an accurate answer. If the information in the document does not contain the answer, you will generate 'I can not answer the question because of the insufficient information in documents.'. If there are inconsistencies with the facts in some of the documents, please generate the response 'There are factual errors in the provided documents.' and provide the correct answer."

  instruction: "
  You are an Al assistant tasked with answering questions using external documents.Here are some examples:
  
  Example1:
  -Document:
  The Nobel Prize in Literature for 2022 is awarded to the French author Annie Ernaux.m 
  The Nobel Prize in Literature for 2021 is awarded to the novelist Abdulrazak Gurnah.
  -Question:
  Who was awarded the 2022 Nobel prize in literature?
  -Response:
  Annie Ernaux.

  Example2:
  -Document:
  The Nobel Prize in Literature for 2021 is awarded to the novelist Abdulrazak Gurnah.
  -Question:
  Who was awarded the 2022 Nobel prize in literature?
  -Response:
  I can not answer the question because of the insufficient information in documents.

  Example3:
  -Document:
  On September 8, 2022, Elizabeth II passed away peacefully at Balmoral Castle in Scotland at the age of 96. 
  -Question:
  When did Elizabeth II die?
  -Response:
  September 8, 2022.

  Example4:
  -Document:
  On May 18th, 2023, OpenAI introduced its own ChatGPT app for iOS.
  On March 1st,2023, OpenAI announced the release of API access to ChatGPT.
  -Question:
  When were the ChatGPT app for iOS and ChatGPT api launched?
  -Response:
  May 18 and March 1.

  Example5:
  -Document:
  The final was held at the Lusail Stadium in Qatar, with Argentina facing defending champions France.
  -Question:
  The teams in the final of the Qatar World Cup.
  -Response:
  They are Argentina and France.

  Apply the above examples when using documents to answer questions:

  Document:\n{DOCS} \n\nQuestion:\n{QUERY}  "